# Generated by Django 5.2.5 on 2025-11-04 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroceryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("quantity", models.CharField(blank=True, max_length=60)),
                ("units", models.CharField(blank=True, max_length=30)),
                ("description", models.TextField(blank=True)),
                ("purchased", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["purchased", "-updated_at"],
            },
        ),
    ]
