# Generated by Django 5.2.5 on 2025-11-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groceryitem",
            name="units",
        ),
    ]
