# Generated by Django 5.2.5 on 2025-11-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_groceryitem_units"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groceryitem",
            options={"ordering": ["purchased", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="groceryitem",
            name="name",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
