# Generated by Django 5.2.5 on 2025-11-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_groceryitem_options_alter_groceryitem_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="groceryitem",
            name="unit",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
